#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Oct 29, 2022 02:09:09 PM +0330  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *


class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("772x675+660+210")
        top.minsize(120, 1)
        top.maxsize(1924, 1041)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")

        self.top = top
        self.checks_1 = tk.StringVar()
        self.checks_2 = tk.StringVar()
        self.checks_3 = tk.StringVar()

        self.Open = tk.Button(self.top)
        self.Open.place(relx=0.013, rely=0.015, height=44, width=47)
        self.Open.configure(activebackground="#ececec")
        self.Open.configure(activeforeground="#000000")
        self.Open.configure(background="#d9d9d9")
        self.Open.configure(compound='left')
        self.Open.configure(disabledforeground="#a3a3a3")
        self.Open.configure(foreground="#000000")
        self.Open.configure(highlightbackground="#d9d9d9")
        self.Open.configure(highlightcolor="black")
        self.Open.configure(pady="0")
        self.Open.configure(text='''Open''')

        self.Decompiler = tk.Button(self.top)
        self.Decompiler.place(relx=0.078, rely=0.015, height=44, width=47)
        self.Decompiler.configure(activebackground="#ececec")
        self.Decompiler.configure(activeforeground="#000000")
        self.Decompiler.configure(background="#d9d9d9")
        self.Decompiler.configure(compound='left')
        self.Decompiler.configure(disabledforeground="#a3a3a3")
        self.Decompiler.configure(foreground="#000000")
        self.Decompiler.configure(highlightbackground="#d9d9d9")
        self.Decompiler.configure(highlightcolor="black")
        self.Decompiler.configure(pady="0")
        self.Decompiler.configure(text='''Decompiler''')

        self.Exit = tk.Button(self.top)
        self.Exit.place(relx=0.142, rely=0.015, height=44, width=47)
        self.Exit.configure(activebackground="#ececec")
        self.Exit.configure(activeforeground="#000000")
        self.Exit.configure(background="#d9d9d9")
        self.Exit.configure(compound='left')
        self.Exit.configure(disabledforeground="#a3a3a3")
        self.Exit.configure(foreground="#000000")
        self.Exit.configure(highlightbackground="#d9d9d9")
        self.Exit.configure(highlightcolor="black")
        self.Exit.configure(pady="0")
        self.Exit.configure(text='''Exit''')

        self.TSeparator1 = ttk.Separator(self.top)
        self.TSeparator1.place(relx=0.181, rely=0.116,  relheight=0.862)
        self.TSeparator1.configure(orient="vertical")

        self.TSeparator2 = ttk.Separator(self.top)
        self.TSeparator2.place(relx=0.181, rely=0.116,  relwidth=0.815)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.menubar.add_checkbutton(
                variable=self.checks_1,
                compound="left",
                label="File")
        self.menubar.add_checkbutton(
                variable=self.checks_2,
                compound="left",
                label="Decompile")
        self.menubar.add_checkbutton(
                variable=self.checks_3,
                compound="left",
                label="About")

        self.TSeparator3 = ttk.Separator(self.top)
        self.TSeparator3.place(relx=0.583, rely=0.116,  relheight=0.877)
        self.TSeparator3.configure(orient="vertical")

        self.Listbox1 = tk.Listbox(self.top)
        self.Listbox1.place(relx=0.181, rely=0.116, relheight=0.88
                , relwidth=0.407)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")

        self.Listbox2 = tk.Listbox(self.top)
        self.Listbox2.place(relx=0.583, rely=0.116, relheight=0.88
                , relwidth=0.407)
        self.Listbox2.configure(background="white")
        self.Listbox2.configure(disabledforeground="#a3a3a3")
        self.Listbox2.configure(font="TkFixedFont")
        self.Listbox2.configure(foreground="#000000")
        self.style.mainloop()




